name: zappy_patrick_customer CI&CD setup

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Also trigger on page_build, as well as release created events

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run ng -- build --base-href /dev/customer/
#     - name: Deploy to Server
#       uses: easingthemes/ssh-deploy@v2.1.5
#       env:
#           SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#           SOURCE: "dist/Angular-8-Starter/"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           TARGET: ${{ secrets.REMOTE_TARGET }}
    - name: deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: ${{ secrets.REMOTE_USER }}
        server: ${{ secrets.REMOTE_HOST }}
        ssh_private_key: ${{ secrets.SERVER_SSH_KEY }} 
        local_path: 'dist/Angular-8-Starter/*'
        remote_path: '/var/www/zappy.tericsoft.com/dev/customer'
        args: '-o ConnectTimeout=5'
